# Generated by Django 5.1.3 on 2024-11-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lasoblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newblog',
            name='blogTitle',
            field=models.TextField(blank=True, null=True),
        ),
    ]
