# Generated by Django 5.1.3 on 2024-11-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lasoblog', '0002_newblog_blogtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='newblog',
            name='blogimage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
